# Generated by Django 4.0 on 2021-12-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_file_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-created_at',)},
        ),
    ]
